# Generated by Django 5.2.11 on 2026-02-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tfa_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='tfa_verified',
            field=models.BooleanField(default=False, verbose_name='2FA verified'),
        ),
    ]
