# Generated by Django 5.2.11 on 2026-02-25 05:37

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tfa_enabled_user_tfa_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='+[country code][number]x[extension]', max_length=31, verbose_name='Phone number'),
        ),
    ]
